export const F = {
  eventName: { key: "eventName", label: "Tadbir nomi", type: "text" as const, required: true },
  eventDate: { key: "eventDate", label: "Sana", type: "date" as const, required: true },
  organization: { key: "organization", label: "Tashkilot", type: "text" as const },
  logo: { key: "logo", label: "Logotip", type: "file" as const, hint: "PNG, SVG" },
  signature: { key: "signature", label: "Imzo", type: "file" as const },
  stamp: { key: "stamp", label: "Muhr", type: "file" as const },
  description: { key: "description", label: "Tavsif / matn", type: "textarea" as const },
  fullName: { key: "fullName", label: "Ism familiya", type: "text" as const, required: true },
  position: { key: "position", label: "Lavozim", type: "text" as const },
  venue: { key: "venue", label: "Manzil / zal", type: "text" as const },
  photo: { key: "photo", label: "Rasm (3x4)", type: "file" as const },
  primaryColor: { key: "primaryColor", label: "Asosiy rang", type: "color" as const },
  secondaryColor: { key: "secondaryColor", label: "Qo‘shimcha rang", type: "color" as const },
  title: { key: "title", label: "Sarlavha", type: "text" as const, required: true },
  subtitle: { key: "subtitle", label: "Pastki sarlavha", type: "text" as const },
  qrUrl: { key: "qrUrl", label: "QR havola (URL)", type: "url" as const },
  excelMode: {
    key: "inputMode",
    label: "Ma’lumot kiritish",
    type: "select" as const,
    options: ["Excel yuklash", "Qo‘lda to‘ldirish"],
    required: true,
  },
  programRows: {
    key: "sessions",
    label: "Kun / sessiyalar",
    type: "repeater" as const,
    repeaterFields: [
      { key: "day", label: "Kun", type: "date" as const },
      { key: "time", label: "Vaqt", type: "time" as const },
      { key: "topic", label: "Mavzu", type: "text" as const, required: true },
      { key: "speaker", label: "Spiker", type: "text" as const },
    ],
  },
  sponsors: { key: "sponsors", label: "Homiylar ro‘yxati", type: "textarea" as const },
  partners: { key: "partners", label: "Hamkorlar", type: "textarea" as const },
  dimensions: {
    key: "size",
    label: "O‘lcham",
    type: "select" as const,
    options: ["A4", "A3", "85x200 roll-up", "Custom"],
  },
  hashtag: { key: "hashtag", label: "Hashtag", type: "text" as const },
  cta: { key: "cta", label: "Chaqiruv (CTA)", type: "text" as const },
};

export const preset = {
  certificate: [F.fullName, F.eventName, F.organization, F.logo, F.signature, F.eventDate, F.description],
  diploma: [F.fullName, F.eventName, F.organization, F.logo, F.signature, F.eventDate, F.description],
  thanks: [F.fullName, F.eventName, F.organization, F.logo, F.signature, F.eventDate, F.description],
  badge: [F.fullName, F.position, F.organization, F.photo, F.eventName, F.eventDate],
  businessCard: [F.fullName, F.position, F.organization, F.logo, { key: "phone", label: "Telefon", type: "text" as const }, { key: "email", label: "Email", type: "text" as const }],
  invitation: [F.fullName, F.eventName, F.eventDate, F.venue, F.organization, F.logo, F.description],
  flyer: [F.title, F.subtitle, F.eventName, F.eventDate, F.venue, F.logo, F.description],
  poster: [F.title, F.subtitle, F.eventName, F.eventDate, F.logo, F.description, F.dimensions],
  scientificPoster: [F.title, F.fullName, F.organization, { key: "abstract", label: "Annotatsiya", type: "textarea" as const }, F.logo],
  programBook: [F.excelMode, F.programRows, F.eventName, F.logo],
  proceedings: [F.excelMode, { key: "articles", label: "Maqolalar (sarlavha, muallif)", type: "textarea" as const }, F.eventName, F.logo],
  catalogDoc: [F.title, F.eventName, F.description, F.logo, F.excelMode],
  reportBook: [F.title, F.eventName, F.organization, F.description, F.logo],
  photoAlbum: [F.title, F.eventName, F.eventDate, { key: "photosZip", label: "Rasmlar arxivi (ZIP)", type: "file" as const }],
  folder: [F.fullName, F.eventName, F.organization, F.logo],
  rollup: [F.title, F.eventName, F.logo, F.sponsors, F.dimensions],
  pressWall: [F.title, F.eventName, F.logo, F.sponsors, F.partners, F.dimensions],
  stageBackdrop: [F.title, F.eventName, F.logo, F.dimensions],
  led: [F.title, F.eventName, F.logo, { key: "resolution", label: "Resolution", type: "text" as const, placeholder: "1920x1080" }],
  openingSlide: [F.title, F.subtitle, F.eventName, F.logo],
  powerpoint: [F.title, F.eventName, F.excelMode, F.programRows, F.logo],
  tableTent: [F.fullName, F.organization, F.logo],
  navigation: [{ key: "signText", label: "Yo‘nalish matni", type: "text" as const, required: true }, F.venue, F.logo],
  registrationDesk: [F.title, F.eventName, F.logo, F.qrUrl],
  qrCard: [F.title, F.qrUrl, F.eventName, F.logo],
  sponsorBanner: [F.title, F.sponsors, F.logo, F.dimensions],
  partnerBanner: [F.title, F.partners, F.logo, F.dimensions],
  socialPost: [F.title, F.eventName, F.hashtag, F.cta, F.logo],
  instagramStory: [F.title, F.eventName, F.hashtag, F.logo],
  telegramBanner: [F.title, F.eventName, F.cta, F.logo],
  linkedinBanner: [F.title, F.subtitle, F.eventName, F.logo],
  emailBanner: [F.title, F.subtitle, F.eventName, F.cta, F.logo],
  pressKit: [F.title, F.eventName, F.description, F.logo, { key: "pressContact", label: "Press kontakt", type: "text" as const }],
  videoIntro: [F.title, F.eventName, F.logo, F.description],
  videoOutro: [F.title, F.eventName, F.logo, { key: "credits", label: "Titrlar matni", type: "textarea" as const }],
  lowerThirds: [F.fullName, F.position, F.organization, F.primaryColor],
  brandBook: [F.eventName, F.logo, F.primaryColor, F.secondaryColor, { key: "fonts", label: "Shriftlar", type: "text" as const }],
  colorSystem: [F.primaryColor, F.secondaryColor, { key: "accent", label: "Accent rang", type: "color" as const }],
  typographyGuide: [{ key: "headingFont", label: "Sarlavha shrifti", type: "text" as const }, { key: "bodyFont", label: "Asosiy shrift", type: "text" as const }],
  letterhead: [F.organization, F.logo, { key: "address", label: "Manzil", type: "textarea" as const }],
  envelope: [F.organization, F.logo, { key: "recipient", label: "Qabul qiluvchi", type: "text" as const }],
  diplomaCover: [F.eventName, F.fullName, F.logo],
  certFolder: [F.eventName, F.organization, F.logo],
  souvenirs: [F.title, F.logo, { key: "items", label: "Mahsulotlar (ruchka, bloknot...)", type: "textarea" as const }],
  stickers: [F.eventName, F.logo, { key: "stickerText", label: "Stiker matni", type: "text" as const }],
  nameTag: [F.fullName, F.organization, F.position, F.logo],
  finalReport: [F.title, F.eventName, F.organization, F.description, F.excelMode],
  photoCatalog: [F.title, F.eventName, F.eventDate, { key: "photoList", label: "Foto ro‘yxati", type: "textarea" as const }],
  videoPresentation: [F.title, F.eventName, F.logo, { key: "videoFile", label: "Video / storyboard", type: "file" as const }],
  conferenceLogo: [F.eventName, F.organization, F.logo, F.primaryColor, F.secondaryColor, F.description],
};
