import type { Template } from '@/types/template'

const now = Date.now()

function daysAgo(days: number): string {
  return new Date(now - days * 24 * 60 * 60 * 1000).toISOString()
}

export interface MockTemplate extends Template {
  description: string
  popularity: number
}

export const MOCK_TEMPLATES: MockTemplate[] = [
  {
    id: 'cert-001',
    name: 'Klassik Sertifikat',
    nameUz: 'Klassik Sertifikat',
    category: 'CERTIFICATE',
    eventType: 'CONFERENCE',
    isPremium: false,
    previewUrl: '',
    tags: ['klassik', 'rasmiy', 'konferentsiya', 'sertifikat'],
    description: 'Rasmiy konferentsiyalar uchun klassik sertifikat dizayni.',
    popularity: 98,
    createdAt: daysAgo(2),
  },
  {
    id: 'cert-002',
    name: 'Zamonaviy Sertifikat',
    nameUz: 'Zamonaviy Sertifikat',
    category: 'CERTIFICATE',
    eventType: 'CONFERENCE',
    isPremium: false,
    previewUrl: '',
    tags: ['zamonaviy', 'minimalist', 'sertifikat'],
    description: 'Minimal chiziqlar va zamonaviy tipografiya.',
    popularity: 87,
    createdAt: daysAgo(5),
  },
  {
    id: 'cert-003',
    name: 'Premium Oltin Sertifikat',
    nameUz: 'Premium Oltin Sertifikat',
    category: 'CERTIFICATE',
    eventType: 'CONFERENCE',
    isPremium: true,
    previewUrl: '',
    tags: ['premium', 'oltin', 'hashamatli', 'sertifikat'],
    description: 'Hashamatli oltin ramka va premium finish.',
    popularity: 76,
    createdAt: daysAgo(12),
  },
  {
    id: 'cert-004',
    name: 'Ilmiy Sertifikat',
    nameUz: 'Ilmiy Sertifikat',
    category: 'CERTIFICATE',
    eventType: 'SCIENTIFIC',
    isPremium: false,
    previewUrl: '',
    tags: ['ilmiy', 'sertifikat', 'universitet'],
    description: 'Ilmiy anjumanlar va tadqiqot uchrashuvlari uchun.',
    popularity: 64,
    createdAt: daysAgo(8),
  },
  {
    id: 'cert-005',
    name: 'Seminar Sertifikati',
    nameUz: 'Seminar Sertifikati',
    category: 'CERTIFICATE',
    eventType: 'SEMINAR',
    isPremium: false,
    previewUrl: '',
    tags: ['seminar', 'sertifikat'],
    description: 'Qisqa muddatli seminarlar uchun mos.',
    popularity: 55,
    createdAt: daysAgo(15),
  },
  {
    id: 'cert-006',
    name: 'Korporativ Sertifikat',
    nameUz: 'Korporativ Sertifikat',
    category: 'CERTIFICATE',
    eventType: 'CORPORATE',
    isPremium: false,
    previewUrl: '',
    tags: ['korporativ', 'sertifikat'],
    description: 'Kompaniya brendi bilan moslashtiriladigan shablon.',
    popularity: 71,
    createdAt: daysAgo(20),
  },
  {
    id: 'cert-007',
    name: 'Ta\'lim Sertifikati',
    nameUz: "Ta'lim Sertifikati",
    category: 'CERTIFICATE',
    eventType: 'EDUCATIONAL',
    isPremium: false,
    previewUrl: '',
    tags: ['talim', 'sertifikat', 'kurs'],
    description: "O'quv kurslari va treninglar uchun.",
    popularity: 62,
    createdAt: daysAgo(25),
  },
  {
    id: 'cert-008',
    name: 'Forum Sertifikati PRO',
    nameUz: 'Forum Sertifikati PRO',
    category: 'CERTIFICATE',
    eventType: 'FORUM',
    isPremium: true,
    previewUrl: '',
    tags: ['forum', 'premium', 'sertifikat'],
    description: 'Yirik forumlar uchun premium dizayn.',
    popularity: 48,
    createdAt: daysAgo(30),
  },
  {
    id: 'badge-001',
    name: 'Minimal Nishon',
    nameUz: 'Minimal Nishon',
    category: 'BADGE',
    eventType: null,
    isPremium: false,
    previewUrl: '',
    tags: ['minimal', 'toza', 'nishon', 'badge'],
    description: 'Sodda va toza ishtirokchi nishoni.',
    popularity: 92,
    createdAt: daysAgo(3),
  },
  {
    id: 'badge-002',
    name: 'Korporativ Nishon',
    nameUz: 'Korporativ Nishon',
    category: 'BADGE',
    eventType: 'CORPORATE',
    isPremium: false,
    previewUrl: '',
    tags: ['korporativ', 'professional', 'nishon'],
    description: 'Korporativ tadbirlar uchun professional badge.',
    popularity: 80,
    createdAt: daysAgo(7),
  },
  {
    id: 'badge-003',
    name: 'Konferentsiya Nishoni',
    nameUz: 'Konferentsiya Nishoni',
    category: 'BADGE',
    eventType: 'CONFERENCE',
    isPremium: false,
    previewUrl: '',
    tags: ['konferentsiya', 'nishon'],
    description: 'Katta konferentsiyalar uchun standart format.',
    popularity: 74,
    createdAt: daysAgo(11),
  },
  {
    id: 'badge-004',
    name: 'VIP Nishon PRO',
    nameUz: 'VIP Nishon PRO',
    category: 'BADGE',
    eventType: 'CORPORATE',
    isPremium: true,
    previewUrl: '',
    tags: ['vip', 'premium', 'nishon'],
    description: 'VIP mehmonlar uchun premium nishon.',
    popularity: 45,
    createdAt: daysAgo(18),
  },
  {
    id: 'badge-005',
    name: 'Ilmiy Nishon',
    nameUz: 'Ilmiy Nishon',
    category: 'BADGE',
    eventType: 'SCIENTIFIC',
    isPremium: false,
    previewUrl: '',
    tags: ['ilmiy', 'nishon'],
    description: 'Ilmiy tadbirlar uchun mos dizayn.',
    popularity: 58,
    createdAt: daysAgo(22),
  },
  {
    id: 'badge-006',
    name: 'Rangli Nishon',
    nameUz: 'Rangli Nishon',
    category: 'BADGE',
    eventType: null,
    isPremium: false,
    previewUrl: '',
    tags: ['rangli', 'yoshlar', 'nishon'],
    description: 'Yorqin ranglar bilan ajralib turadi.',
    popularity: 66,
    createdAt: daysAgo(28),
  },
  {
    id: 'inv-001',
    name: 'Rasmiy Taklifnoma',
    nameUz: 'Rasmiy Taklifnoma',
    category: 'INVITATION',
    eventType: 'CONFERENCE',
    isPremium: false,
    previewUrl: '',
    tags: ['rasmiy', 'konferentsiya', 'taklifnoma'],
    description: 'QR kodli rasmiy taklifnoma shablon.',
    popularity: 85,
    createdAt: daysAgo(4),
  },
  {
    id: 'inv-002',
    name: 'Zamonaviy Taklifnoma',
    nameUz: 'Zamonaviy Taklifnoma',
    category: 'INVITATION',
    eventType: 'SEMINAR',
    isPremium: false,
    previewUrl: '',
    tags: ['zamonaviy', 'taklifnoma'],
    description: 'Zamonaviy tipografiya va geometrik fon.',
    popularity: 72,
    createdAt: daysAgo(9),
  },
  {
    id: 'inv-003',
    name: 'Premium Taklifnoma',
    nameUz: 'Premium Taklifnoma',
    category: 'INVITATION',
    eventType: 'CORPORATE',
    isPremium: true,
    previewUrl: '',
    tags: ['premium', 'taklifnoma'],
    description: 'Hashamatli korporativ tadbirlar uchun.',
    popularity: 51,
    createdAt: daysAgo(16),
  },
  {
    id: 'inv-004',
    name: 'Forum Taklifnomasi',
    nameUz: 'Forum Taklifnomasi',
    category: 'INVITATION',
    eventType: 'FORUM',
    isPremium: false,
    previewUrl: '',
    tags: ['forum', 'taklifnoma'],
    description: 'Forum va muhokama tadbirlari uchun.',
    popularity: 59,
    createdAt: daysAgo(21),
  },
  {
    id: 'inv-005',
    name: 'Masterklass Taklifnomasi',
    nameUz: 'Masterklass Taklifnomasi',
    category: 'INVITATION',
    eventType: 'WORKSHOP',
    isPremium: false,
    previewUrl: '',
    tags: ['masterklass', 'taklifnoma'],
    description: 'Workshop va masterklasslar uchun.',
    popularity: 63,
    createdAt: daysAgo(26),
  },
  {
    id: 'inv-006',
    name: 'VIP Taklifnoma PRO',
    nameUz: 'VIP Taklifnoma PRO',
    category: 'INVITATION',
    eventType: 'CORPORATE',
    isPremium: true,
    previewUrl: '',
    tags: ['vip', 'premium', 'taklifnoma'],
    description: 'VIP mehmonlar uchun eksklyuziv dizayn.',
    popularity: 42,
    createdAt: daysAgo(32),
  },
  {
    id: 'flyer-001',
    name: 'A5 Flayer — Zamonaviy',
    nameUz: 'A5 Flayer — Zamonaviy',
    category: 'FLYER',
    eventType: null,
    isPremium: false,
    previewUrl: '',
    tags: ['a5', 'zamonaviy', 'flayer'],
    description: 'A5 formatdagi zamonaviy tadbir flyeri.',
    popularity: 78,
    createdAt: daysAgo(6),
  },
  {
    id: 'flyer-002',
    name: 'Korporativ Flayer',
    nameUz: 'Korporativ Flayer',
    category: 'FLYER',
    eventType: 'CORPORATE',
    isPremium: false,
    previewUrl: '',
    tags: ['korporativ', 'flayer'],
    description: 'Korporativ tadbirlar uchun professional flayer.',
    popularity: 69,
    createdAt: daysAgo(13),
  },
  {
    id: 'flyer-003',
    name: 'Ilmiy Flayer',
    nameUz: 'Ilmiy Flayer',
    category: 'FLYER',
    eventType: 'SCIENTIFIC',
    isPremium: false,
    previewUrl: '',
    tags: ['ilmiy', 'flayer'],
    description: 'Ilmiy konferensiyalar uchun.',
    popularity: 57,
    createdAt: daysAgo(19),
  },
  {
    id: 'flyer-004',
    name: 'Premium Flayer PRO',
    nameUz: 'Premium Flayer PRO',
    category: 'FLYER',
    eventType: 'CONFERENCE',
    isPremium: true,
    previewUrl: '',
    tags: ['premium', 'flayer'],
    description: 'Premium finish bilan flayer dizayni.',
    popularity: 44,
    createdAt: daysAgo(27),
  },
  {
    id: 'flyer-005',
    name: 'Seminar Flayeri',
    nameUz: 'Seminar Flayeri',
    category: 'FLYER',
    eventType: 'SEMINAR',
    isPremium: false,
    previewUrl: '',
    tags: ['seminar', 'flayer'],
    description: 'Seminarlar uchun ixcham flayer.',
    popularity: 61,
    createdAt: daysAgo(33),
  },
  {
    id: 'flyer-006',
    name: 'Yorqin Flayer',
    nameUz: 'Yorqin Flayer',
    category: 'FLYER',
    eventType: null,
    isPremium: false,
    previewUrl: '',
    tags: ['yorqin', 'flayer'],
    description: 'Diqqatni tortuvchi yorqin ranglar.',
    popularity: 53,
    createdAt: daysAgo(35),
  },
  {
    id: 'poster-001',
    name: 'A2 Poster — Klassik',
    nameUz: 'A2 Poster — Klassik',
    category: 'POSTER',
    eventType: 'CONFERENCE',
    isPremium: false,
    previewUrl: '',
    tags: ['poster', 'a2', 'klassik'],
    description: 'A2/A3 formatdagi klassik poster.',
    popularity: 70,
    createdAt: daysAgo(10),
  },
  {
    id: 'poster-002',
    name: 'Zamonaviy Poster',
    nameUz: 'Zamonaviy Poster',
    category: 'POSTER',
    eventType: null,
    isPremium: false,
    previewUrl: '',
    tags: ['poster', 'zamonaviy'],
    description: 'Minimal zamonaviy poster dizayni.',
    popularity: 65,
    createdAt: daysAgo(17),
  },
  {
    id: 'poster-003',
    name: 'Ilmiy Poster',
    nameUz: 'Ilmiy Poster',
    category: 'POSTER',
    eventType: 'SCIENTIFIC',
    isPremium: false,
    previewUrl: '',
    tags: ['poster', 'ilmiy'],
    description: 'Ilmiy tadbirlar uchun poster.',
    popularity: 56,
    createdAt: daysAgo(24),
  },
  {
    id: 'poster-004',
    name: 'Premium Poster PRO',
    nameUz: 'Premium Poster PRO',
    category: 'POSTER',
    eventType: 'CONFERENCE',
    isPremium: true,
    previewUrl: '',
    tags: ['poster', 'premium'],
    description: 'Yirik tadbirlar uchun premium poster.',
    popularity: 40,
    createdAt: daysAgo(36),
  },
  {
    id: 'social-001',
    name: 'Instagram Post',
    nameUz: 'Instagram Post',
    category: 'SOCIAL_MEDIA',
    eventType: null,
    isPremium: false,
    previewUrl: '',
    tags: ['instagram', '1x1', 'ijtimoiy'],
    description: 'Instagram uchun 1:1 format post.',
    popularity: 94,
    createdAt: daysAgo(1),
  },
  {
    id: 'social-002',
    name: 'Telegram Banner',
    nameUz: 'Telegram Banner',
    category: 'SOCIAL_MEDIA',
    eventType: null,
    isPremium: false,
    previewUrl: '',
    tags: ['telegram', 'banner', 'ijtimoiy'],
    description: 'Telegram kanallar uchun banner.',
    popularity: 88,
    createdAt: daysAgo(3),
  },
  {
    id: 'social-003',
    name: 'LinkedIn Post',
    nameUz: 'LinkedIn Post',
    category: 'SOCIAL_MEDIA',
    eventType: 'CORPORATE',
    isPremium: false,
    previewUrl: '',
    tags: ['linkedin', 'ijtimoiy'],
    description: 'Korporativ LinkedIn postlari uchun.',
    popularity: 67,
    createdAt: daysAgo(14),
  },
  {
    id: 'social-004',
    name: 'Stories Template',
    nameUz: 'Stories Shablon',
    category: 'SOCIAL_MEDIA',
    eventType: null,
    isPremium: false,
    previewUrl: '',
    tags: ['stories', 'instagram', 'ijtimoiy'],
    description: 'Instagram/Facebook stories formati.',
    popularity: 82,
    createdAt: daysAgo(8),
  },
  {
    id: 'social-005',
    name: 'Facebook Event Cover',
    nameUz: 'Facebook Event Cover',
    category: 'SOCIAL_MEDIA',
    eventType: null,
    isPremium: false,
    previewUrl: '',
    tags: ['facebook', 'cover', 'ijtimoiy'],
    description: 'Facebook tadbir muqovasi.',
    popularity: 60,
    createdAt: daysAgo(23),
  },
  {
    id: 'social-006',
    name: 'Social Pack PRO',
    nameUz: 'Social Pack PRO',
    category: 'SOCIAL_MEDIA',
    eventType: null,
    isPremium: true,
    previewUrl: '',
    tags: ['premium', 'pack', 'ijtimoiy'],
    description: 'Barcha ijtimoiy tarmoqlar uchun to\'plam.',
    popularity: 52,
    createdAt: daysAgo(29),
  },
  {
    id: 'email-001',
    name: 'Email Banner — Klassik',
    nameUz: 'Email Banner — Klassik',
    category: 'EMAIL_BANNER',
    eventType: 'CONFERENCE',
    isPremium: false,
    previewUrl: '',
    tags: ['email', 'banner'],
    description: 'Email xabarlar uchun klassik banner.',
    popularity: 68,
    createdAt: daysAgo(12),
  },
  {
    id: 'email-002',
    name: 'Email Banner — Zamonaviy',
    nameUz: 'Email Banner — Zamonaviy',
    category: 'EMAIL_BANNER',
    eventType: null,
    isPremium: false,
    previewUrl: '',
    tags: ['email', 'zamonaviy'],
    description: 'Zamonaviy email marketing banneri.',
    popularity: 54,
    createdAt: daysAgo(31),
  },
  {
    id: 'email-003',
    name: 'Newsletter Header',
    nameUz: 'Newsletter Header',
    category: 'EMAIL_BANNER',
    eventType: 'CORPORATE',
    isPremium: false,
    previewUrl: '',
    tags: ['newsletter', 'email'],
    description: 'Kompaniya newsletter sarlavhasi.',
    popularity: 49,
    createdAt: daysAgo(34),
  },
  {
    id: 'email-004',
    name: 'Premium Email PRO',
    nameUz: 'Premium Email PRO',
    category: 'EMAIL_BANNER',
    eventType: null,
    isPremium: true,
    previewUrl: '',
    tags: ['email', 'premium'],
    description: 'Premium email kampaniyalar uchun.',
    popularity: 38,
    createdAt: daysAgo(40),
  },
  {
    id: 'tent-001',
    name: 'Stol Kartasi — Minimal',
    nameUz: 'Stol Kartasi — Minimal',
    category: 'TABLE_TENT',
    eventType: null,
    isPremium: false,
    previewUrl: '',
    tags: ['stol', 'table tent'],
    description: 'Minimal stol kartasi dizayni.',
    popularity: 73,
    createdAt: daysAgo(11),
  },
  {
    id: 'tent-002',
    name: 'Stol Kartasi — Korporativ',
    nameUz: 'Stol Kartasi — Korporativ',
    category: 'TABLE_TENT',
    eventType: 'CORPORATE',
    isPremium: false,
    previewUrl: '',
    tags: ['stol', 'korporativ'],
    description: 'Korporativ tadbirlar uchun stol kartasi.',
    popularity: 58,
    createdAt: daysAgo(26),
  },
  {
    id: 'tent-003',
    name: 'Raqamli Stol Kartasi',
    nameUz: 'Raqamli Stol Kartasi',
    category: 'TABLE_TENT',
    eventType: null,
    isPremium: false,
    previewUrl: '',
    tags: ['stol', 'raqam'],
    description: 'Stol raqami va ism bilan.',
    popularity: 50,
    createdAt: daysAgo(37),
  },
  {
    id: 'tent-004',
    name: 'Premium Stol Kartasi',
    nameUz: 'Premium Stol Kartasi',
    category: 'TABLE_TENT',
    eventType: 'CONFERENCE',
    isPremium: true,
    previewUrl: '',
    tags: ['stol', 'premium'],
    description: 'Premium tadbirlar uchun stol kartasi.',
    popularity: 36,
    createdAt: daysAgo(42),
  },
  {
    id: 'rollup-001',
    name: 'Roll-up — Klassik',
    nameUz: 'Roll-up — Klassik',
    category: 'ROLL_UP',
    eventType: 'CONFERENCE',
    isPremium: false,
    previewUrl: '',
    tags: ['rollup', 'banner'],
    description: '85x200 cm klassik roll-up banner.',
    popularity: 75,
    createdAt: daysAgo(9),
  },
  {
    id: 'rollup-002',
    name: 'Roll-up — Zamonaviy',
    nameUz: 'Roll-up — Zamonaviy',
    category: 'ROLL_UP',
    eventType: null,
    isPremium: false,
    previewUrl: '',
    tags: ['rollup', 'zamonaviy'],
    description: 'Zamonaviy roll-up dizayni.',
    popularity: 62,
    createdAt: daysAgo(20),
  },
  {
    id: 'rollup-003',
    name: 'Roll-up PRO',
    nameUz: 'Roll-up PRO',
    category: 'ROLL_UP',
    eventType: 'CORPORATE',
    isPremium: true,
    previewUrl: '',
    tags: ['rollup', 'premium'],
    description: 'Premium roll-up banner shablon.',
    popularity: 41,
    createdAt: daysAgo(38),
  },
  {
    id: 'rollup-004',
    name: 'Ilmiy Roll-up',
    nameUz: 'Ilmiy Roll-up',
    category: 'ROLL_UP',
    eventType: 'SCIENTIFIC',
    isPremium: true,
    previewUrl: '',
    tags: ['rollup', 'ilmiy'],
    description: 'Ilmiy konferensiyalar uchun roll-up.',
    popularity: 35,
    createdAt: daysAgo(45),
  },
]

export function getCategoryCounts(): Record<string, number> {
  const counts: Record<string, number> = { ALL: MOCK_TEMPLATES.length }
  for (const template of MOCK_TEMPLATES) {
    counts[template.category] = (counts[template.category] ?? 0) + 1
  }
  return counts
}
