import { artboardForProduct } from "./artboards"
import type { DesignTemplateDefinition } from "./types"

const ab = artboardForProduct

/** Classic formal certificate — navy frame, gold accents, signatures + QR */
const certificateTemplate: DesignTemplateDefinition = {
  productId: "certificate",
  title: "Certificate — Classic Formal",
  artboard: ab("certificate"),
  layers: [
    { kind: "background", id: "bg", name: "Fon", x: 0, y: 0, width: 560, height: 396, fill: "#0a1628" },
    {
      kind: "shape",
      id: "glow-tr",
      shape: "ellipse",
      x: 380,
      y: -60,
      width: 220,
      height: 220,
      fill: "#c9a22733",
      opacity: 0.9,
    },
    {
      kind: "shape",
      id: "glow-bl",
      shape: "ellipse",
      x: -40,
      y: 280,
      width: 160,
      height: 160,
      fill: "#2563eb22",
    },
    {
      kind: "shape",
      id: "frame-outer",
      shape: "rect",
      x: 28,
      y: 24,
      width: 504,
      height: 348,
      fill: "transparent",
      stroke: "#c9a227",
      strokeWidth: 2,
    },
    {
      kind: "shape",
      id: "frame-inner",
      shape: "rect",
      x: 40,
      y: 36,
      width: 480,
      height: 324,
      fill: "transparent",
      stroke: "#c9a22766",
      strokeWidth: 1,
    },
    {
      kind: "shape",
      id: "accent-line",
      shape: "line",
      x: 180,
      y: 118,
      width: 200,
      height: 2,
      fill: "transparent",
      stroke: "#c9a227",
      strokeWidth: 2,
    },
    { kind: "logo", id: "logo", name: "Logo", x: 230, y: 44, width: 100, height: 56 },
    {
      kind: "text",
      id: "subtitle",
      name: "Subtitr",
      placeholder: "{{subtitle}}",
      x: 80,
      y: 108,
      width: 400,
      height: 22,
      fontSize: 11,
      fontWeight: 600,
      color: "#c9a227",
      textAlign: "center",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "text",
      id: "title",
      name: "Sarlavha",
      placeholder: "SERTIFIKAT",
      x: 80,
      y: 128,
      width: 400,
      height: 36,
      fontSize: 28,
      fontWeight: 700,
      color: "#ffffff",
      textAlign: "center",
      fontFamily: "Georgia, serif",
    },
    {
      kind: "text",
      id: "presented",
      name: "Matn",
      placeholder: "Quyidagi shaxsga taqdim etiladi",
      x: 120,
      y: 168,
      width: 320,
      height: 20,
      fontSize: 11,
      fontWeight: 400,
      color: "#94a3b8",
      textAlign: "center",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "text",
      id: "full-name",
      name: "Ism familiya",
      placeholder: "{{full_name}}",
      x: 60,
      y: 192,
      width: 440,
      height: 44,
      fontSize: 32,
      fontWeight: 700,
      color: "#ffffff",
      textAlign: "center",
      fontFamily: "Georgia, serif",
    },
    {
      kind: "text",
      id: "organization",
      name: "Tashkilot",
      placeholder: "{{organization}}",
      x: 80,
      y: 240,
      width: 400,
      height: 24,
      fontSize: 14,
      fontWeight: 500,
      color: "#cbd5e1",
      textAlign: "center",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "text",
      id: "position",
      name: "Lavozim",
      placeholder: "{{position}}",
      x: 100,
      y: 264,
      width: 360,
      height: 20,
      fontSize: 12,
      fontWeight: 400,
      color: "#64748b",
      textAlign: "center",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "text",
      id: "event-name",
      name: "Tadbir",
      placeholder: "{{event_name}}",
      x: 80,
      y: 292,
      width: 400,
      height: 28,
      fontSize: 15,
      fontWeight: 600,
      color: "#e2e8f0",
      textAlign: "center",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "text",
      id: "date",
      name: "Sana",
      placeholder: "{{date}}",
      x: 200,
      y: 322,
      width: 160,
      height: 18,
      fontSize: 11,
      fontWeight: 500,
      color: "#64748b",
      textAlign: "center",
      fontFamily: "Inter, sans-serif",
    },
    { kind: "signature", id: "signature-1", name: "Imzo 1", x: 72, y: 318, width: 110, height: 44 },
    {
      kind: "text",
      id: "sig-label-1",
      name: "Imzo yorlig‘i",
      placeholder: "Direktor",
      x: 72,
      y: 362,
      width: 110,
      height: 14,
      fontSize: 9,
      fontWeight: 500,
      color: "#64748b",
      textAlign: "center",
      fontFamily: "Inter, sans-serif",
    },
    { kind: "signature", id: "signature-2", name: "Imzo 2", x: 378, y: 318, width: 110, height: 44 },
    {
      kind: "text",
      id: "sig-label-2",
      name: "Imzo yorlig‘i 2",
      placeholder: "Rais",
      x: 378,
      y: 362,
      width: 110,
      height: 14,
      fontSize: 9,
      fontWeight: 500,
      color: "#64748b",
      textAlign: "center",
      fontFamily: "Inter, sans-serif",
    },
    { kind: "stamp", id: "stamp", name: "Muhr", x: 244, y: 310, width: 72, height: 72 },
    { kind: "qr", id: "qr", name: "QR tekshiruv", x: 468, y: 300, width: 72, height: 72, placeholder: "https://gildia.uz/verify/{{full_name}}" },
  ],
}

/** Horizontal badge — photo, stripe, QR */
const badgeTemplate: DesignTemplateDefinition = {
  productId: "badge",
  title: "Badge — Conference ID",
  artboard: ab("badge"),
  layers: [
    { kind: "background", id: "bg", name: "Fon", x: 0, y: 0, width: 340, height: 214, fill: "#ffffff" },
    { kind: "shape", id: "stripe", shape: "rect", x: 0, y: 0, width: 12, height: 214, fill: "#2563eb" },
    {
      kind: "shape",
      id: "stripe-accent",
      shape: "rect",
      x: 12,
      y: 0,
      width: 4,
      height: 214,
      fill: "#0a1628",
    },
    {
      kind: "shape",
      id: "photo-ring",
      shape: "ellipse",
      x: 28,
      y: 52,
      width: 88,
      height: 88,
      fill: "#f1f5f9",
      stroke: "#2563eb",
      strokeWidth: 2,
    },
    { kind: "image", id: "photo", name: "Foto", x: 32, y: 56, width: 80, height: 80, objectFit: "cover" },
    { kind: "logo", id: "logo", name: "Logo", x: 248, y: 16, width: 72, height: 36 },
    {
      kind: "text",
      id: "full-name",
      name: "Ism",
      placeholder: "{{full_name}}",
      x: 128,
      y: 56,
      width: 196,
      height: 32,
      fontSize: 18,
      fontWeight: 700,
      color: "#0a1628",
      textAlign: "left",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "text",
      id: "position",
      name: "Lavozim",
      placeholder: "{{position}}",
      x: 128,
      y: 88,
      width: 196,
      height: 20,
      fontSize: 11,
      fontWeight: 500,
      color: "#64748b",
      textAlign: "left",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "text",
      id: "organization",
      name: "Tashkilot",
      placeholder: "{{organization}}",
      x: 128,
      y: 108,
      width: 196,
      height: 18,
      fontSize: 10,
      fontWeight: 400,
      color: "#94a3b8",
      textAlign: "left",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "shape",
      id: "divider",
      shape: "line",
      x: 128,
      y: 132,
      width: 120,
      height: 1,
      fill: "transparent",
      stroke: "#e2e8f0",
      strokeWidth: 1,
    },
    {
      kind: "text",
      id: "event-name",
      name: "Tadbir",
      placeholder: "{{event_name}}",
      x: 128,
      y: 140,
      width: 140,
      height: 36,
      fontSize: 11,
      fontWeight: 700,
      color: "#2563eb",
      textAlign: "left",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "text",
      id: "date",
      name: "Sana",
      placeholder: "{{date}}",
      x: 128,
      y: 176,
      width: 100,
      height: 16,
      fontSize: 9,
      fontWeight: 500,
      color: "#94a3b8",
      textAlign: "left",
      fontFamily: "Inter, sans-serif",
    },
    { kind: "qr", id: "qr", x: 268, y: 148, width: 56, height: 56 },
  ],
}

/** Elegant invitation — cream, ornamental corners */
const invitationTemplate: DesignTemplateDefinition = {
  productId: "invitation",
  title: "Invitation — Elegant",
  artboard: ab("invitation"),
  layers: [
    { kind: "background", id: "bg", name: "Fon", x: 0, y: 0, width: 280, height: 400, fill: "#faf6f0" },
    {
      kind: "shape",
      id: "border",
      shape: "rect",
      x: 16,
      y: 16,
      width: 248,
      height: 368,
      fill: "transparent",
      stroke: "#8b6914",
      strokeWidth: 1,
    },
    {
      kind: "shape",
      id: "corner-tl",
      shape: "ellipse",
      x: 8,
      y: 8,
      width: 48,
      height: 48,
      fill: "#c9a22722",
    },
    {
      kind: "shape",
      id: "corner-br",
      shape: "ellipse",
      x: 224,
      y: 344,
      width: 56,
      height: 56,
      fill: "#c9a22718",
    },
    { kind: "logo", id: "logo", name: "Logo", x: 100, y: 36, width: 80, height: 48 },
    {
      kind: "text",
      id: "label",
      name: "Yorliq",
      placeholder: "RASMIY TAKLIFNOMA",
      x: 32,
      y: 96,
      width: 216,
      height: 18,
      fontSize: 9,
      fontWeight: 700,
      color: "#8b6914",
      textAlign: "center",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "text",
      id: "guest",
      name: "Mehmon",
      placeholder: "{{full_name}}",
      x: 24,
      y: 128,
      width: 232,
      height: 40,
      fontSize: 26,
      fontWeight: 700,
      color: "#1c1917",
      textAlign: "center",
      fontFamily: "Georgia, serif",
    },
    {
      kind: "text",
      id: "position",
      name: "Lavozim",
      placeholder: "{{position}}",
      x: 32,
      y: 172,
      width: 216,
      height: 20,
      fontSize: 12,
      fontWeight: 400,
      color: "#78716c",
      textAlign: "center",
      fontFamily: "Georgia, serif",
    },
    {
      kind: "shape",
      id: "ornament",
      shape: "line",
      x: 90,
      y: 200,
      width: 100,
      height: 1,
      fill: "transparent",
      stroke: "#c9a227",
      strokeWidth: 1,
    },
    {
      kind: "text",
      id: "body",
      name: "Matn",
      placeholder: "Sizni quyidagi tadbirga samimiy taklif qilamiz",
      x: 28,
      y: 212,
      width: 224,
      height: 48,
      fontSize: 11,
      fontWeight: 400,
      color: "#57534e",
      textAlign: "center",
      fontFamily: "Georgia, serif",
    },
    {
      kind: "text",
      id: "event-name",
      name: "Tadbir",
      placeholder: "{{event_name}}",
      x: 24,
      y: 268,
      width: 232,
      height: 48,
      fontSize: 16,
      fontWeight: 700,
      color: "#0a1628",
      textAlign: "center",
      fontFamily: "Georgia, serif",
    },
    {
      kind: "text",
      id: "date",
      name: "Sana va joy",
      placeholder: "{{date}}",
      x: 32,
      y: 320,
      width: 216,
      height: 24,
      fontSize: 13,
      fontWeight: 600,
      color: "#8b6914",
      textAlign: "center",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "text",
      id: "organization",
      name: "Tashkilot",
      placeholder: "{{organization}}",
      x: 32,
      y: 352,
      width: 216,
      height: 18,
      fontSize: 10,
      fontWeight: 500,
      color: "#a8a29e",
      textAlign: "center",
      fontFamily: "Inter, sans-serif",
    },
  ],
}

/** Marketing flyer — bold gradient hero */
const flyerTemplate: DesignTemplateDefinition = {
  productId: "flyer",
  title: "Flyer — Event Announcement",
  artboard: ab("flyer"),
  layers: [
    {
      kind: "shape",
      id: "bg-gradient-top",
      shape: "rect",
      x: 0,
      y: 0,
      width: 396,
      height: 320,
      fill: "#2563eb",
    },
    {
      kind: "shape",
      id: "bg-gradient-bottom",
      shape: "rect",
      x: 0,
      y: 280,
      width: 396,
      height: 280,
      fill: "#0a1628",
    },
    {
      kind: "shape",
      id: "blob",
      shape: "ellipse",
      x: 260,
      y: 120,
      width: 180,
      height: 180,
      fill: "#ffffff18",
    },
    {
      kind: "shape",
      id: "accent-bar",
      shape: "rect",
      x: 32,
      y: 48,
      width: 6,
      height: 48,
      fill: "#fbbf24",
    },
    { kind: "logo", id: "logo", name: "Logo", x: 32, y: 32, width: 88, height: 48 },
    {
      kind: "text",
      id: "event-tag",
      name: "Teg",
      placeholder: "KONFERENSIYA • {{date}}",
      x: 32,
      y: 108,
      width: 320,
      height: 16,
      fontSize: 10,
      fontWeight: 700,
      color: "#bfdbfe",
      textAlign: "left",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "text",
      id: "headline",
      name: "Sarlavha",
      placeholder: "{{event_name}}",
      x: 32,
      y: 128,
      width: 332,
      height: 120,
      fontSize: 36,
      fontWeight: 800,
      color: "#ffffff",
      textAlign: "left",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "text",
      id: "subtitle",
      name: "Subtitr",
      placeholder: "{{subtitle}}",
      x: 32,
      y: 252,
      width: 300,
      height: 40,
      fontSize: 14,
      fontWeight: 500,
      color: "#e2e8f0",
      textAlign: "left",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "shape",
      id: "info-card",
      shape: "rect",
      x: 24,
      y: 340,
      width: 348,
      height: 180,
      fill: "#ffffff",
      stroke: "#e2e8f0",
      strokeWidth: 1,
    },
    {
      kind: "text",
      id: "speaker",
      name: "Spiker",
      placeholder: "{{full_name}}",
      x: 40,
      y: 364,
      width: 200,
      height: 28,
      fontSize: 18,
      fontWeight: 700,
      color: "#0a1628",
      textAlign: "left",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "text",
      id: "organization",
      name: "Tashkilot",
      placeholder: "{{organization}}",
      x: 40,
      y: 396,
      width: 220,
      height: 20,
      fontSize: 12,
      fontWeight: 500,
      color: "#64748b",
      textAlign: "left",
      fontFamily: "Inter, sans-serif",
    },
  ],
}

/** Poster — large typographic stack */
const posterTemplate: DesignTemplateDefinition = {
  productId: "poster",
  title: "Poster — Conference Hero",
  artboard: ab("poster"),
  layers: [
    { kind: "background", id: "bg", name: "Fon", x: 0, y: 0, width: 420, height: 594, fill: "#0f172a" },
    {
      kind: "shape",
      id: "diagonal",
      shape: "triangle",
      x: 0,
      y: 0,
      width: 420,
      height: 280,
      fill: "#2563eb",
    },
    {
      kind: "shape",
      id: "circle-deco",
      shape: "ellipse",
      x: 300,
      y: 380,
      width: 160,
      height: 160,
      fill: "#fbbf2422",
    },
    { kind: "logo", id: "logo", name: "Logo", x: 36, y: 36, width: 100, height: 56 },
    {
      kind: "text",
      id: "year",
      name: "Yil",
      placeholder: "2026",
      x: 300,
      y: 48,
      width: 80,
      height: 48,
      fontSize: 40,
      fontWeight: 900,
      color: "#fbbf24",
      textAlign: "right",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "text",
      id: "headline",
      name: "Sarlavha",
      placeholder: "{{event_name}}",
      x: 32,
      y: 120,
      width: 356,
      height: 200,
      fontSize: 42,
      fontWeight: 900,
      color: "#ffffff",
      textAlign: "left",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "text",
      id: "subtitle",
      name: "Subtitr",
      placeholder: "{{subtitle}}",
      x: 32,
      y: 328,
      width: 340,
      height: 56,
      fontSize: 18,
      fontWeight: 500,
      color: "#94a3b8",
      textAlign: "left",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "shape",
      id: "cta-bar",
      shape: "rect",
      x: 32,
      y: 420,
      width: 200,
      height: 44,
      fill: "#fbbf24",
    },
    {
      kind: "text",
      id: "cta",
      name: "CTA",
      placeholder: "RO‘YXATDAN O‘TING",
      x: 32,
      y: 420,
      width: 200,
      height: 44,
      fontSize: 13,
      fontWeight: 800,
      color: "#0a1628",
      textAlign: "center",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "text",
      id: "date",
      name: "Sana",
      placeholder: "{{date}} • {{organization}}",
      x: 32,
      y: 520,
      width: 356,
      height: 24,
      fontSize: 12,
      fontWeight: 600,
      color: "#64748b",
      textAlign: "left",
      fontFamily: "Inter, sans-serif",
    },
    { kind: "qr", id: "qr", x: 328, y: 500, width: 72, height: 72 },
  ],
}

/** Program book cover — split burgundy / white */
const programBookTemplate: DesignTemplateDefinition = {
  productId: "program-book",
  title: "Program Book — Cover",
  artboard: ab("program-book"),
  layers: [
    { kind: "shape", id: "bg-left", shape: "rect", x: 0, y: 0, width: 160, height: 560, fill: "#7f1d1d" },
    { kind: "shape", id: "bg-right", shape: "rect", x: 160, y: 0, width: 236, height: 560, fill: "#fafaf9" },
    {
      kind: "shape",
      id: "spine-line",
      shape: "line",
      x: 160,
      y: 40,
      width: 1,
      height: 480,
      fill: "transparent",
      stroke: "#c9a227",
      strokeWidth: 2,
    },
    { kind: "logo", id: "logo", name: "Logo", x: 32, y: 48, width: 96, height: 56 },
    {
      kind: "text",
      id: "label",
      name: "Yorliq",
      placeholder: "PROGRAM BOOK",
      x: 24,
      y: 200,
      width: 112,
      height: 80,
      fontSize: 11,
      fontWeight: 700,
      color: "#fecaca",
      textAlign: "left",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "text",
      id: "event-name",
      name: "Tadbir",
      placeholder: "{{event_name}}",
      x: 184,
      y: 160,
      width: 196,
      height: 160,
      fontSize: 28,
      fontWeight: 800,
      color: "#0a1628",
      textAlign: "left",
      fontFamily: "Georgia, serif",
    },
    {
      kind: "text",
      id: "subtitle",
      name: "Subtitr",
      placeholder: "{{subtitle}}",
      x: 184,
      y: 328,
      width: 196,
      height: 48,
      fontSize: 13,
      fontWeight: 500,
      color: "#78716c",
      textAlign: "left",
      fontFamily: "Georgia, serif",
    },
    {
      kind: "text",
      id: "date",
      name: "Sana",
      placeholder: "{{date}}",
      x: 184,
      y: 400,
      width: 160,
      height: 24,
      fontSize: 14,
      fontWeight: 600,
      color: "#7f1d1d",
      textAlign: "left",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "text",
      id: "organization",
      name: "Tashkilot",
      placeholder: "{{organization}}",
      x: 184,
      y: 480,
      width: 196,
      height: 40,
      fontSize: 11,
      fontWeight: 500,
      color: "#a8a29e",
      textAlign: "left",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "shape",
      id: "deco-bar",
      shape: "rect",
      x: 184,
      y: 140,
      width: 48,
      height: 4,
      fill: "#c9a227",
    },
  ],
}

/** Roll-up — vertical brand tower */
const rollupTemplate: DesignTemplateDefinition = {
  productId: "rollup-banner",
  title: "Roll-up — Registration",
  artboard: ab("rollup-banner"),
  layers: [
    { kind: "shape", id: "bg-top", shape: "rect", x: 0, y: 0, width: 200, height: 240, fill: "#2563eb" },
    { kind: "shape", id: "bg-bottom", shape: "rect", x: 0, y: 240, width: 200, height: 240, fill: "#0a1628" },
    {
      kind: "shape",
      id: "ring",
      shape: "ellipse",
      x: 50,
      y: 60,
      width: 100,
      height: 100,
      fill: "#ffffff15",
      stroke: "#ffffff44",
      strokeWidth: 2,
    },
    { kind: "logo", id: "logo", name: "Logo", x: 60, y: 80, width: 80, height: 56 },
    {
      kind: "text",
      id: "event-name",
      name: "Tadbir",
      placeholder: "{{event_name}}",
      x: 16,
      y: 180,
      width: 168,
      height: 120,
      fontSize: 22,
      fontWeight: 800,
      color: "#ffffff",
      textAlign: "center",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "text",
      id: "subtitle",
      name: "Subtitr",
      placeholder: "{{subtitle}}",
      x: 16,
      y: 300,
      width: 168,
      height: 48,
      fontSize: 11,
      fontWeight: 500,
      color: "#bfdbfe",
      textAlign: "center",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "text",
      id: "date",
      name: "Sana",
      placeholder: "{{date}}",
      x: 16,
      y: 360,
      width: 168,
      height: 20,
      fontSize: 10,
      fontWeight: 600,
      color: "#94a3b8",
      textAlign: "center",
      fontFamily: "Inter, sans-serif",
    },
    { kind: "qr", id: "qr", x: 64, y: 400, width: 72, height: 72 },
    {
      kind: "text",
      id: "organization",
      name: "Tashkilot",
      placeholder: "{{organization}}",
      x: 12,
      y: 448,
      width: 176,
      height: 24,
      fontSize: 9,
      fontWeight: 500,
      color: "#64748b",
      textAlign: "center",
      fontFamily: "Inter, sans-serif",
    },
  ],
}

/** Press wall — sponsor grid + central hero */
const pressWallTemplate: DesignTemplateDefinition = {
  productId: "press-wall",
  title: "Press Wall — Media Backdrop",
  artboard: ab("press-wall"),
  layers: [
    { kind: "background", id: "bg", name: "Fon", x: 0, y: 0, width: 480, height: 320, fill: "#f8fafc" },
    {
      kind: "shape",
      id: "header-band",
      shape: "rect",
      x: 0,
      y: 0,
      width: 480,
      height: 72,
      fill: "#0a1628",
    },
    { kind: "logo", id: "logo-main", name: "Asosiy logo", x: 196, y: 12, width: 88, height: 48 },
    {
      kind: "text",
      id: "event-name",
      name: "Tadbir",
      placeholder: "{{event_name}}",
      x: 40,
      y: 88,
      width: 400,
      height: 40,
      fontSize: 26,
      fontWeight: 800,
      color: "#0a1628",
      textAlign: "center",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "text",
      id: "subtitle",
      name: "Subtitr",
      placeholder: "{{subtitle}}",
      x: 60,
      y: 128,
      width: 360,
      height: 24,
      fontSize: 12,
      fontWeight: 500,
      color: "#64748b",
      textAlign: "center",
      fontFamily: "Inter, sans-serif",
    },
    { kind: "logo", id: "sponsor-1", name: "Sponsor 1", x: 24, y: 168, width: 96, height: 48 },
    { kind: "logo", id: "sponsor-2", name: "Sponsor 2", x: 136, y: 168, width: 96, height: 48 },
    { kind: "logo", id: "sponsor-3", name: "Sponsor 3", x: 248, y: 168, width: 96, height: 48 },
    { kind: "logo", id: "sponsor-4", name: "Sponsor 4", x: 360, y: 168, width: 96, height: 48 },
    { kind: "logo", id: "sponsor-5", name: "Sponsor 5", x: 80, y: 232, width: 96, height: 48 },
    { kind: "logo", id: "sponsor-6", name: "Sponsor 6", x: 192, y: 232, width: 96, height: 48 },
    { kind: "logo", id: "sponsor-7", name: "Sponsor 7", x: 304, y: 232, width: 96, height: 48 },
    {
      kind: "text",
      id: "date",
      name: "Sana",
      placeholder: "{{date}}",
      x: 160,
      y: 292,
      width: 160,
      height: 18,
      fontSize: 10,
      fontWeight: 600,
      color: "#94a3b8",
      textAlign: "center",
      fontFamily: "Inter, sans-serif",
    },
  ],
}

/** Stage backdrop — wide cinematic typography */
const stageBackdropTemplate: DesignTemplateDefinition = {
  productId: "stage-backdrop",
  title: "Stage Backdrop — Opening",
  artboard: ab("stage-backdrop"),
  layers: [
    { kind: "background", id: "bg", name: "Fon", x: 0, y: 0, width: 560, height: 336, fill: "#020617" },
    {
      kind: "shape",
      id: "beam-left",
      shape: "triangle",
      x: 0,
      y: 0,
      width: 280,
      height: 336,
      fill: "#1e3a8a",
      opacity: 0.85,
    },
    {
      kind: "shape",
      id: "beam-right",
      shape: "ellipse",
      x: 400,
      y: -40,
      width: 200,
      height: 200,
      fill: "#2563eb55",
    },
    {
      kind: "shape",
      id: "floor-glow",
      shape: "ellipse",
      x: 180,
      y: 260,
      width: 200,
      height: 40,
      fill: "#38bdf822",
    },
    { kind: "logo", id: "logo", name: "Logo", x: 248, y: 32, width: 64, height: 40 },
    {
      kind: "text",
      id: "event-name",
      name: "Tadbir",
      placeholder: "{{event_name}}",
      x: 40,
      y: 88,
      width: 480,
      height: 80,
      fontSize: 44,
      fontWeight: 900,
      color: "#ffffff",
      textAlign: "center",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "text",
      id: "subtitle",
      name: "Subtitr",
      placeholder: "{{subtitle}}",
      x: 80,
      y: 172,
      width: 400,
      height: 32,
      fontSize: 16,
      fontWeight: 500,
      color: "#7dd3fc",
      textAlign: "center",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "shape",
      id: "accent-line",
      shape: "line",
      x: 200,
      y: 220,
      width: 160,
      height: 2,
      fill: "transparent",
      stroke: "#fbbf24",
      strokeWidth: 3,
    },
    {
      kind: "text",
      id: "date",
      name: "Sana",
      placeholder: "{{date}}",
      x: 160,
      y: 236,
      width: 240,
      height: 28,
      fontSize: 18,
      fontWeight: 700,
      color: "#fbbf24",
      textAlign: "center",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "text",
      id: "organization",
      name: "Tashkilot",
      placeholder: "{{organization}}",
      x: 120,
      y: 280,
      width: 320,
      height: 20,
      fontSize: 11,
      fontWeight: 500,
      color: "#64748b",
      textAlign: "center",
      fontFamily: "Inter, sans-serif",
    },
  ],
}

/** Social post — square bold layout with photo circle */
const socialPostTemplate: DesignTemplateDefinition = {
  productId: "social-media-post",
  title: "Social Post — Square Announcement",
  artboard: ab("social-media-post"),
  layers: [
    {
      kind: "background",
      id: "bg",
      name: "Fon",
      x: 0,
      y: 0,
      width: 400,
      height: 400,
      fill: "#4c1d95",
    },
    {
      kind: "shape",
      id: "bg-accent",
      shape: "rect",
      x: 0,
      y: 240,
      width: 400,
      height: 160,
      fill: "#0a1628",
    },
    {
      kind: "shape",
      id: "circle-photo",
      shape: "ellipse",
      x: 140,
      y: 48,
      width: 120,
      height: 120,
      fill: "#ffffff22",
      stroke: "#ffffff66",
      strokeWidth: 3,
    },
    { kind: "image", id: "photo", name: "Foto / speaker", x: 148, y: 56, width: 104, height: 104, objectFit: "cover" },
    { kind: "logo", id: "logo", name: "Logo", x: 24, y: 24, width: 64, height: 36 },
    {
      kind: "text",
      id: "event-name",
      name: "Tadbir",
      placeholder: "{{event_name}}",
      x: 24,
      y: 188,
      width: 352,
      height: 56,
      fontSize: 22,
      fontWeight: 800,
      color: "#ffffff",
      textAlign: "left",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "text",
      id: "subtitle",
      name: "Subtitr",
      placeholder: "{{subtitle}}",
      x: 24,
      y: 248,
      width: 280,
      height: 40,
      fontSize: 13,
      fontWeight: 500,
      color: "#e9d5ff",
      textAlign: "left",
      fontFamily: "Inter, sans-serif",
    },
    {
      kind: "text",
      id: "date",
      name: "Sana",
      placeholder: "{{date}}",
      x: 24,
      y: 340,
      width: 200,
      height: 20,
      fontSize: 11,
      fontWeight: 600,
      color: "#94a3b8",
      textAlign: "left",
      fontFamily: "Inter, sans-serif",
    },
    { kind: "qr", id: "qr", x: 308, y: 312, width: 72, height: 72 },
  ],
}

export const DESIGN_TEMPLATE_DEFINITIONS: DesignTemplateDefinition[] = [
  certificateTemplate,
  badgeTemplate,
  invitationTemplate,
  flyerTemplate,
  posterTemplate,
  programBookTemplate,
  rollupTemplate,
  pressWallTemplate,
  stageBackdropTemplate,
  socialPostTemplate,
]

export const DESIGN_TEMPLATE_BY_PRODUCT_ID = Object.fromEntries(
  DESIGN_TEMPLATE_DEFINITIONS.map((t) => [t.productId, t])
) as Record<string, DesignTemplateDefinition>
