import type { CatalogCategory, CatalogCategorySlug, CatalogProduct, PreviewTone } from "./types"

/** Single source of truth — all Gildia design products */
export type ProductCatalogDefinition = {
  id: string
  name: string
  description: string
  format: string
  categorySlug: CatalogCategorySlug
  previewTone: PreviewTone
  isPrint?: boolean
  isOnline?: boolean
  isPremium?: boolean
}

export const PRODUCT_CATALOG_CATEGORIES: CatalogCategory[] = [
  { slug: "documents", name: "Documents", icon: "📜" },
  { slug: "identification", name: "ID & badges", icon: "🪪" },
  { slug: "invitations-marketing", name: "Invitations & print", icon: "✉️" },
  { slug: "programs", name: "Programs & books", icon: "📑" },
  { slug: "large-format", name: "Large format", icon: "📐" },
  { slug: "presentations", name: "Presentations", icon: "🖥️" },
  { slug: "social", name: "Social & email", icon: "📱" },
  { slug: "brand", name: "Brand system", icon: "🎨" },
  { slug: "video", name: "Video graphics", icon: "🎬" },
]

const TONE_TO_VARIANT: Record<PreviewTone, CatalogProduct["variant"]> = {
  document: "certificate",
  card: "badge",
  print: "flyer",
  large: "rollup",
  digital: "social",
  brand: "brand-kit",
  video: "social",
}

function slugify(name: string) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
}

/** All design products — add new entries here only */
export const PRODUCT_CATALOG_DEFINITIONS: ProductCatalogDefinition[] = [
  {
    id: "certificate",
    name: "Certificate",
    description: "Rasmiy ishtirok yoki bitiruv sertifikati — imzo, muhr va QR bilan.",
    format: "A4 • Landscape",
    categorySlug: "documents",
    previewTone: "document",
    isPrint: true,
  },
  {
    id: "diploma",
    name: "Diploma",
    description: "Akademik yoki professional diplom maketi — premium ko‘rinish.",
    format: "A4 • Portrait",
    categorySlug: "documents",
    previewTone: "document",
    isPrint: true,
    isPremium: true,
  },
  {
    id: "thank-you-letter",
    name: "Thank you letter",
    description: "Minnatdorchilik xati — rasmiy tadbir yoki hamkorlik uchun.",
    format: "A4 • Portrait",
    categorySlug: "documents",
    previewTone: "document",
    isPrint: true,
  },
  {
    id: "badge",
    name: "Badge",
    description: "Konferensiya yoki forum ishtirokchisi bejigi — foto va QR bilan.",
    format: "90 × 54 mm",
    categorySlug: "identification",
    previewTone: "card",
    isPrint: true,
  },
  {
    id: "business-card",
    name: "Business card",
    description: "Vizitka — spiker, tashkilot yoki delegat uchun.",
    format: "90 × 50 mm",
    categorySlug: "identification",
    previewTone: "card",
    isPrint: true,
  },
  {
    id: "invitation",
    name: "Invitation",
    description: "Rasmiy taklifnoma — VIP, delegat yoki mehmon uchun.",
    format: "A5 • Portrait",
    categorySlug: "invitations-marketing",
    previewTone: "print",
    isPrint: true,
  },
  {
    id: "flyer",
    name: "Flyer",
    description: "Tadbir e’loni — tez tarqatish va ko‘rinish uchun.",
    format: "A4 • Portrait",
    categorySlug: "invitations-marketing",
    previewTone: "print",
    isPrint: true,
  },
  {
    id: "poster",
    name: "Poster",
    description: "Konferensiya afishasi yoki e’lon posteri.",
    format: "A1 • Portrait",
    categorySlug: "invitations-marketing",
    previewTone: "print",
    isPrint: true,
  },
  {
    id: "scientific-poster",
    name: "Scientific poster",
    description: "Ilmiy poster — sessiya va poster sessiyalari uchun.",
    format: "A0 • Portrait",
    categorySlug: "invitations-marketing",
    previewTone: "print",
    isPrint: true,
    isPremium: true,
  },
  {
    id: "program-book",
    name: "Program book",
    description: "Konferensiya dasturi — kunlik yoki to‘liq program book.",
    format: "A4 • Booklet",
    categorySlug: "programs",
    previewTone: "document",
    isPrint: true,
  },
  {
    id: "proceedings-book",
    name: "Proceedings book",
    description: "Maqolalar to‘plami — ilmiy konferensiya materiallari.",
    format: "A4 • Book",
    categorySlug: "programs",
    previewTone: "document",
    isPrint: true,
    isPremium: true,
  },
  {
    id: "catalog",
    name: "Catalog",
    description: "Ishtirokchilar, eksponatlar yoki tashkilotlar katalogi.",
    format: "A4 • Multi-page",
    categorySlug: "programs",
    previewTone: "document",
    isPrint: true,
  },
  {
    id: "report-book",
    name: "Report book",
    description: "Tadbir hisobot kitobi — rasmiy natijalar va statistika.",
    format: "A4 • Document",
    categorySlug: "programs",
    previewTone: "document",
    isPrint: true,
  },
  {
    id: "photo-album",
    name: "Photo album",
    description: "Tadbir fotosuratlari albomi — yakuniy material.",
    format: "A4 • Landscape",
    categorySlug: "programs",
    previewTone: "document",
    isPrint: true,
  },
  {
    id: "folder",
    name: "Folder",
    description: "Konferensiya papkasi — materiallar to‘plami uchun.",
    format: "A4 • Folder",
    categorySlug: "programs",
    previewTone: "print",
    isPrint: true,
  },
  {
    id: "rollup-banner",
    name: "Roll-up banner",
    description: "Vertikal roll-up — registratsiya va kirish zonasi.",
    format: "85 × 200 cm",
    categorySlug: "large-format",
    previewTone: "large",
    isPrint: true,
  },
  {
    id: "press-wall",
    name: "Press wall",
    description: "Press-wall / foto fon — media va intervyu uchun.",
    format: "300 × 200 cm",
    categorySlug: "large-format",
    previewTone: "large",
    isPrint: true,
    isPremium: true,
  },
  {
    id: "stage-backdrop",
    name: "Stage backdrop",
    description: "Asosiy sahna foni — panel va ochilish marosimi.",
    format: "400 × 240 cm",
    categorySlug: "large-format",
    previewTone: "large",
    isPrint: true,
    isPremium: true,
  },
  {
    id: "led-screen-design",
    name: "LED screen design",
    description: "LED ekran grafikasi — sahna va zal ekranlari.",
    format: "1920 × 1080 px",
    categorySlug: "large-format",
    previewTone: "large",
    isOnline: true,
  },
  {
    id: "opening-slide",
    name: "Opening slide",
    description: "Ochilish slaydi — prezentatsiya va marosim boshlanishi.",
    format: "16:9 • Slide",
    categorySlug: "presentations",
    previewTone: "digital",
    isOnline: true,
  },
  {
    id: "powerpoint",
    name: "PowerPoint",
    description: "Prezentatsiya shablon to‘plami — spiker va moderator uchun.",
    format: "16:9 • PPTX",
    categorySlug: "presentations",
    previewTone: "digital",
    isOnline: true,
  },
  {
    id: "table-tent",
    name: "Table tent",
    description: "Stol ustuni / table tent — o‘tirish joylari va VIP stollar.",
    format: "A5 • Tent",
    categorySlug: "invitations-marketing",
    previewTone: "print",
    isPrint: true,
  },
  {
    id: "navigation-signs",
    name: "Navigation signs",
    description: "Yo‘naltirish tablichkalari — zal, sessiya va servis zonalar.",
    format: "A3 / A2",
    categorySlug: "large-format",
    previewTone: "print",
    isPrint: true,
  },
  {
    id: "registration-stand",
    name: "Registration stand",
    description: "Registratsiya stendi dizayni — kirish va badge berish.",
    format: "100 × 200 cm",
    categorySlug: "large-format",
    previewTone: "large",
    isPrint: true,
  },
  {
    id: "qr-cards",
    name: "QR cards",
    description: "QR ro‘yxatga yozilish yoki kirish kartasi.",
    format: "90 × 54 mm",
    categorySlug: "identification",
    previewTone: "card",
    isPrint: true,
    isOnline: true,
  },
  {
    id: "sponsor-banner",
    name: "Sponsor banner",
    description: "Sponsor brendi banneri — zal va press zona.",
    format: "Custom • Print",
    categorySlug: "large-format",
    previewTone: "large",
    isPrint: true,
  },
  {
    id: "partner-banner",
    name: "Partner banner",
    description: "Hamkor tashkilot banneri — bir xil tadbir uslubida.",
    format: "Custom • Print",
    categorySlug: "large-format",
    previewTone: "large",
    isPrint: true,
  },
  {
    id: "social-media-post",
    name: "Social media post",
    description: "Umumiy ijtimoiy tarmoq posti — e’lon va eslatma.",
    format: "1080 × 1080 px",
    categorySlug: "social",
    previewTone: "digital",
    isOnline: true,
  },
  {
    id: "instagram-story",
    name: "Instagram Story",
    description: "Instagram Stories formatida vertikal e’lon.",
    format: "1080 × 1920 px",
    categorySlug: "social",
    previewTone: "digital",
    isOnline: true,
  },
  {
    id: "telegram-banner",
    name: "Telegram banner",
    description: "Telegram kanal yoki guruh banneri.",
    format: "1280 × 720 px",
    categorySlug: "social",
    previewTone: "digital",
    isOnline: true,
  },
  {
    id: "linkedin-banner",
    name: "LinkedIn banner",
    description: "LinkedIn profil yoki kompaniya banneri.",
    format: "1584 × 396 px",
    categorySlug: "social",
    previewTone: "digital",
    isOnline: true,
  },
  {
    id: "email-banner",
    name: "Email banner",
    description: "Email xat yoki newsletter banneri.",
    format: "600 × 200 px",
    categorySlug: "social",
    previewTone: "digital",
    isOnline: true,
  },
  {
    id: "press-kit",
    name: "Press kit",
    description: "OAV va media uchun press-kit to‘plami.",
    format: "Multi-asset",
    categorySlug: "brand",
    previewTone: "brand",
    isOnline: true,
    isPremium: true,
  },
  {
    id: "video-intro",
    name: "Video intro",
    description: "Tadbir video intro — ochilish va translatsiya.",
    format: "1920 × 1080 px",
    categorySlug: "video",
    previewTone: "video",
    isOnline: true,
    isPremium: true,
  },
  {
    id: "video-outro",
    name: "Video outro",
    description: "Video outro — yakuniy ekran va kontaktlar.",
    format: "1920 × 1080 px",
    categorySlug: "video",
    previewTone: "video",
    isOnline: true,
    isPremium: true,
  },
  {
    id: "lower-thirds",
    name: "Lower thirds",
    description: "Translatsiya lower thirds — spiker ismi va lavozim.",
    format: "1920 × 1080 px",
    categorySlug: "video",
    previewTone: "video",
    isOnline: true,
  },
  {
    id: "brand-book",
    name: "Brand book",
    description: "To‘liq brendbuk — logo, rang, tipografiya qoidalari.",
    format: "A4 • PDF",
    categorySlug: "brand",
    previewTone: "brand",
    isOnline: true,
    isPremium: true,
  },
  {
    id: "color-system",
    name: "Color system",
    description: "Tadbir rang palitrasi va qo‘llash qo‘llanmasi.",
    format: "Digital guide",
    categorySlug: "brand",
    previewTone: "brand",
    isOnline: true,
  },
  {
    id: "font-guide",
    name: "Font guide",
    description: "Tipografiya qo‘llanmasi — shriftlar va ierarxiya.",
    format: "A4 • PDF",
    categorySlug: "brand",
    previewTone: "brand",
    isOnline: true,
  },
  {
    id: "letterhead",
    name: "Letterhead",
    description: "Rasmiy blank — xat va hujjatlar uchun.",
    format: "A4",
    categorySlug: "documents",
    previewTone: "document",
    isPrint: true,
  },
  {
    id: "envelope",
    name: "Envelope",
    description: "Konvert dizayni — rasmiy yuborish materiallari.",
    format: "DL / C4",
    categorySlug: "documents",
    previewTone: "print",
    isPrint: true,
  },
  {
    id: "diploma-cover",
    name: "Diploma cover",
    description: "Diplom muqovasi — tashqi dizayn va brending.",
    format: "A4 • Cover",
    categorySlug: "documents",
    previewTone: "document",
    isPrint: true,
    isPremium: true,
  },
  {
    id: "certificate-folder",
    name: "Certificate folder",
    description: "Sertifikatlar papkasi — topshirish to‘plami.",
    format: "A4 • Folder",
    categorySlug: "documents",
    previewTone: "print",
    isPrint: true,
  },
  {
    id: "souvenir-designs",
    name: "Souvenir designs",
    description: "Suvenir mahsulotlari dizayni — tadbir brendi bilan.",
    format: "Various",
    categorySlug: "brand",
    previewTone: "brand",
    isPrint: true,
  },
  {
    id: "stickers",
    name: "Stickers",
    description: "Stiker varaqasi — brend yopishqichlari va belgilar.",
    format: "A4 • Sheet",
    categorySlug: "brand",
    previewTone: "print",
    isPrint: true,
  },
  {
    id: "name-tags",
    name: "Name tags",
    description: "Ism yorlig‘i / name tag — networking va zal.",
    format: "90 × 54 mm",
    categorySlug: "identification",
    previewTone: "card",
    isPrint: true,
  },
  {
    id: "final-report",
    name: "Final report",
    description: "Yakuniy hisobot — tadbir natijalari hujjati.",
    format: "A4 • Document",
    categorySlug: "programs",
    previewTone: "document",
    isPrint: true,
  },
  {
    id: "photo-catalog",
    name: "Photo catalog",
    description: "Fotokatalog — tadbir suratlari to‘plami.",
    format: "A4 • Landscape",
    categorySlug: "programs",
    previewTone: "document",
    isPrint: true,
  },
  {
    id: "video-presentation",
    name: "Video presentation",
    description: "Video prezentatsiya grafikasi — fon va titrlar.",
    format: "16:9 • HD",
    categorySlug: "presentations",
    previewTone: "video",
    isOnline: true,
    isPremium: true,
  },
]

function toCatalogProduct(def: ProductCatalogDefinition, index: number): CatalogProduct {
  return {
    id: def.id || slugify(def.name),
    title: def.name,
    description: def.description,
    categorySlug: def.categorySlug,
    format: def.format,
    variant: TONE_TO_VARIANT[def.previewTone],
    previewTone: def.previewTone,
    isPremium: def.isPremium ?? index % 4 === 0,
    isPrint: def.isPrint ?? !["social", "video"].includes(def.categorySlug),
    isOnline: def.isOnline ?? true,
  }
}

export const CATALOG_PRODUCTS: CatalogProduct[] = PRODUCT_CATALOG_DEFINITIONS.map(toCatalogProduct)

export const CATALOG_CATEGORIES = PRODUCT_CATALOG_CATEGORIES

export function getProductById(id: string) {
  return CATALOG_PRODUCTS.find((p) => p.id === id)
}

export function getCategoryBySlug(slug: string) {
  return CATALOG_CATEGORIES.find((c) => c.slug === slug)
}

export function getProductsByCategory(slug: CatalogCategorySlug) {
  return CATALOG_PRODUCTS.filter((p) => p.categorySlug === slug)
}
